### ISSUE TITLE
Only the first music disc successfully works - any others play nothing and have the same texture as the 1st custom disc

### ISSUE THREAD

**Issue by TheGreatLucario** [TeamTernate/infinite-music-discs#108]
While working on adding plenty of music for my server with my friends, I've decided to do a test run with the generator. First I started with one disc to ensure that the generator worked, which it did, properly gave the new music disc the right texture and song, however, when I did a 2nd run and added 4 more discs to overall hear how they sound in game, all 4 of those new discs ended up having the same texture as the first one that worked, and when inserted into a jukebox, played nothing, even when the play command was executed. The disc that was on top of the list that was generated first, however, worked as normal.

**Comment by bradytheinventor** [comment]
It sounds like the game is correctly using your new datapack, but is incorrectly using the old resourcepack instead of the new one. I would delete the old datapack and resourcepack just to be sure, then activate the new resourcepack and `/reload` all datapacks and see if that helps.
