### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by Zomber566** [TeamTernate/infinite-music-discs#113]
I downloaded the latest windows version and when I try to launch the app, it just won't start. I tried running it as administrator and I tried making a shortcut but that didn't do anything. The previous version I had (1.5 I think) worked completely fine with no issues at all.

**Comment by bradytheinventor** [comment]
v1.6 added `multiprocessing`, which converts all of the tracks in parallel. It speeds up pack generation dramatically when it works, but it hasn't been working for a lot of people. I just released v1.6.2 to fix some issues with it, try that and see if your problem goes away.
