### ISSUE TITLE
Resource Pack Not Downloading When Friends Join My World.

### ISSUE THREAD

**Issue by DragonGamer8181** [TeamTernate/infinite-music-discs#120]
Basically, whenever my friends try to join my world they get the prompt to download the pack, but then it says it failed to download. This could have something to do with the fact I'm using the Essential Mod for multiplayer. This is a big issue because my friend isn't great with computers and it takes him a long time to add the pack to his game.

**Comment by bradytheinventor** [comment]
Have you tested that the resourcepack works, like does it work for you if you install it on your own computer? If the resourcepack works then the tool is working fine and it's more of a setup problem. I don't really remember how to set up a resourcepack download, I think you're supposed to upload your pack as a .zip to a file share like Mediafire and then add the link to your server.properties but it's been a while.

**Comment by DragonGamer8181** [comment]
i thought the way the resource packs worked is like if anyone joins it will automatically download it regardless of if you do that, but ill try it anyway. (btw it might be different because im using essential mod to play with friends, as i said in the original post, but ill do some research if your method doesnt work.)

**Comment by bradytheinventor** [comment]
Since this seems like a server configuration problem I'm going to close this issue. But if it turns out to be an app problem feel free to reopen it.
