### ISSUE TITLE
1.20.1 Music Disc 11 plays at the same time Modpack:Better Minecraft[FORGE]

### ISSUE THREAD

**Issue by RundmR** [TeamTernate/infinite-music-discs#137]
I tested on a pure vanilla version of 1.20.1 and it works perfectly fine,but it keeps playing Disc 11 when I try it on a Singleplayer world in
Better Minecraft,I can't figure out what exactly is conflicting and I've run the proper commands.

**Comment by LawdyLuz** [comment]
I have the same problem

**Comment by bradytheinventor** [comment]
Unfortunately I can't guarantee compatibility with every mod and datapack out there. There are a lot of them, after all, and I'm just one person!

I recommend running `/reload` and looking in the game log to make sure the datapack loads. If it doesn't, use the error messages Minecraft prints in the log to figure out which mod is conflicting. You can also try removing mods until the datapack works.

If you decide to undertake this I would be interested to hear what you find. But for now, I'm going to close this issue.

**Comment by LawdyLuz** [comment]
It is fine! Do not feel pressured, i appreciate that you were going out if
your way to make a cool tool like that.
