### ISSUE TITLE
Can't add track names from a file

### ISSUE THREAD

**Issue by JusteRoro** [TeamTernate/infinite-music-discs#138]
I've tried using the same process as shown in this video (https://www.youtube.com/watch?v=9g8SkX4EG1M, at around 1:20), using a "track_names.txt" to name all songs in one go, but when I drag the file into the generator, nothing happens.

Do you have a potential solution to this or is it a bug?

**Comment by bradytheinventor** [comment]
If this is a bug, I've never seen it before. Make sure you drag-dropped your text file directly onto the name text box of an existing track. If it still doesn't work, try removing lines from your text file until it does work to figure out which line is causing the problem.
