### ISSUE TITLE
My custom discs all play disc 11 sound

### ISSUE THREAD

**Issue by ThaQuicekst02** [TeamTernate/infinite-music-discs#139]
did /reload before inserting the disc into the jukebox but it didn't work

https://github.com/TeamTernate/infinite-music-discs/assets/34247603/41d3ed52-df75-4c4a-bafe-704173eb6ac4

**Comment by bradytheinventor** [comment]
When you run `/reload` a yellow message should pop up telling you that the datapack is working. Something else must be preventing the datapack from loading correctly. If you have other mods or datapacks installed, remove them one by one to figure out which one is causing the problem. Or you can look in the game logs for any error messages when you ran `/reload`.
