### ISSUE TITLE
Support for 1.20.5 and up - replace item NBT with components

### ISSUE THREAD

**Issue by ExplosiveGeek77** [TeamTernate/infinite-music-discs#142]
title says it all.

**Comment by bradytheinventor** [comment]
1.20.5 replaced item NBT with a new "components" system and it may take a while to rewrite the datapack to be compatible with the new format. But support for 1.20.5 and up is planned.

**Comment by 500-internal-server-error** [comment]
I managed to debug my way through enough to make the pack run on 1.20.5/6 with the new component system [here on my fork](https://github.com/TeamTernate/infinite-music-discs/compare/v1.6.3...500-internal-server-error:v1.6.3-1.20.6). Not being familiar with the pack internals it took me a bit of `execute as @s run say hi` debugging to find where the pack breaks, but I did eventually get there :)

@bradytheinventor Would you accept my changes if I open a PR, or do you have something diffeent in mind?

**Comment by 500-internal-server-error** [comment]
Ah, they're adding [native support for custom music discs in 1.21](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w21a) :)

**Comment by bradytheinventor** [comment]
@500-internal-server-error Thanks for taking the time to make those changes! However I have already made similar changes on my local copy of the v1.6.3 branch, so there's no need for a pull request. I'm fighting with the creeper loot table generation right now, but I hope to have 1.20.5 support out soon.

Native data-driven music discs is very cool. 1.21 also lets you use components in crafting recipes so it's possible to add crafting recipes for custom music discs as well. It's a little disappointing that my datapack won't be necessary after 1.21, but I suppose the app can still be a convenient frontend for people to generate their custom discs.

**Comment by 500-internal-server-error** [comment]
> However I have already made similar changes on my local copy of the v1.6.3 branch, so there's no need for a pull request.
Ah, ok, no worries.

> but I suppose the app can still be a convenient frontend for people to generate their custom discs.
Yep, I would still use the app if only for its convenience :) There will probably be websites that do it online, but not sure if they will support the drag and drop feature that your app supports to allow easy mass insertion of custom music.

**Comment by 500-internal-server-error** [comment]
> I'm fighting with the creeper loot table generation right now, but I hope to have 1.20.5 support out soon.

@bradytheinventor I've just figured out the creeper loot table myself, if you're still fighting with it :)
