### ISSUE TITLE
Music not working when ran with a command block

### ISSUE THREAD

**Issue by MarleyTheCreeper** [TeamTernate/infinite-music-discs#143]
![2024-05-05_12 52 44](https://github.com/TeamTernate/infinite-music-discs/assets/168966594/45b4a291-c62c-4aaf-9691-3fc6931947c6)
When i type this command in and run it, it wont play the sound, I've tried to target specific blocks, entities and such.
I just can't figure out how to play it with command blocks. (I am on 1.20.6. I havent tested if thats the issue yet.)

**Comment by bradytheinventor** [comment]
If you open the function in a text editor, you'll see a playsound command (for example `playsound minecraft:music_disc.prazkhanalwhip record @s ~ ~ ~ 4 1`). Try running that command in chat. You can change the `@s` selector to something like `@p` or `@a` to hear the sound when it's played from a command block.

If it doesn't work, then 1.20.6 has probably broken the datapack. I'll fix it as soon as I can but there were big datapack changes so it might take a while.
