### ISSUE TITLE
How do I use an animated sprite for the disc sprite?

### ISSUE THREAD

**Issue by DragonGamer8181** [TeamTernate/infinite-music-discs#145]
I don't know if this is where I should ask this but how do I use an animated sprite as the disc sprite? I made a glitchy disc that I'm really proud of but I don't know how to add it in.

**Comment by bradytheinventor** [comment]
The tool can't turn animated textures into Minecraft-compatible animated sprites, but you can manually edit your resourcepack after you've generated it. You'll need to format the frames of your animated texture as a spritesheet and create a `.mcmeta` file to tell Minecraft how to draw the frames: https://minecraft.wiki/w/Resource_pack#Animation
