### ISSUE TITLE
Is there any way to limit the range of the custom record discs?

### ISSUE THREAD

**Issue by joeygp1** [TeamTernate/infinite-music-discs#146]
Hi! I was experimenting with adding custom discs, when I noticed that the range of the custom discs seemed to be infinite. Is there anything I have failed to notice, or is this a quirk from the datapack that might need fixing?
Thanks in advance!

**Comment by bradytheinventor** [comment]
Check the "play tracks from the jukebox block" setting while generating your pack. That will make the disc sounds come from the jukebox block and fall off with distance like vanilla discs.

**Comment by joeygp1** [comment]
It works! Thanks a lot!
