### ISSUE TITLE
Music loud distances away

### ISSUE THREAD

**Issue by Minecraftsam1212** [TeamTernate/infinite-music-discs#147]
how do I make it where the music gets lower as I go away from it? because even when I go 500 blocks away I still hear it

**Comment by bradytheinventor** [comment]
Check the "play tracks from the jukebox block" setting when you generate your pack

**Comment by Minecraftsam1212** [comment]
im pretty sure I did that

**Comment by Minecraftsam1212** [comment]
I inserted the disc inside and it players it but the farther I go the volume remains the same even 500 blocks away

**Comment by Minecraftsam1212** [comment]
hello?

**Comment by Minecraftsam1212** [comment]
still didnt work

**Comment by bradytheinventor** [comment]
Did you re-generate your pack after checking the "play tracks from the jukebox block" setting? Did you remove the old resourcepack and replace it with your new one? Checking that setting is how you make the music discs get quieter with distance.

If you are 100% certain that you checked the setting when generating your pack and it's still not working, please give me some more details like the files you used, what other settings you checked, game version, other datapacks, etc. I can't debug without knowing what you did

**Comment by bradytheinventor** [comment]
Found the problem. In v1.6.2 you need to check 2 settings: "Play tracks from the jukebox block" and "Convert .ogg files instead of copying". Will fix this in the next version

**Comment by Minecraftsam1212** [comment]
So I should do the regular steps and check the "Convert .ogg files instead of copying"? will that work now though?

**Comment by bradytheinventor** [comment]
Yes, in the current (v1.6.2) version of the app, if you check both of the settings I listed when you generate your pack, the tracks should play from the jukebox block
