### ISSUE TITLE
Problems in 1.21 (v.1.8.0)

### ISSUE THREAD

**Issue by thejenja** [TeamTernate/infinite-music-discs#152]
I decided to try building a datapack with a program from another branch and noticed a few issues:

- Instead of three functions (corresponding to three songs) in jukebox_song, only one was created.

- In the function, there's a reference to infinite_music_discs:music_disc.(song name), which shouldn't be there because sounds in Minecraft are defined without the resourcepack name. Indeed, after removing it, the sound appeared and the music worked correctly.

**Comment by bradytheinventor** [comment]
I applaud your enthusiasm but that's a dev branch so yeah it might not work yet. Commit c011fd resolves some of your issues.

FYI Minecraft sounds can be defined in namespaces other than the default `minecraft` namespace, the IMD resourcepack just doesn't do that right now. I want to update the resourcepack to put custom discs in their own namespace so you can have multiple packs without collisions between `sounds.json` etc

**Comment by thejenja** [comment]
Thanks for the help! Good luck with the rest of the development.
