### ISSUE TITLE
doesnt change volume with distance

### ISSUE THREAD

**Issue by altxria** [TeamTernate/infinite-music-discs#2]
is this supposed to happen or is my game glitched?

**Comment by BobTheNerd10** [comment]
I'm unsure if the pack effects any of the data relevant to this but I know that audio for music discs need to have 1 channel (Mono). If they're stereo (2 channels) then they play globally.
You can do this easily in audacity by clicking on the drop-down menu for the song, and then pressing "Split into mono" or something along those lines

**Comment by bradytheinventor** [comment]
Yep, in Minecraft's post-1.14 sound engine, stereo sounds will play globally ("follow" the player) while mono sounds will play at the position they were created. So if your custom music disc uses a stereo track (like most music these days), it will play globally as you observed. Convert to mono with something like Audacity or ffmpeg if you want the discs to play in one spot.

Might add a setting to convert tracks to mono in the app using `pyffmpeg`.
