### ISSUE TITLE
No Audio when turning down Minecraft volume.  

### ISSUE THREAD

**Issue by CoolGuyGit** [TeamTernate/infinite-music-discs#23]
I don't know entirely if this is just my headset or just in general my Minecraft, but whenever i turn my master volume all the way down and back up using the Minecraft audio settings, it just stops playing the disc audio for me.

**Comment by bradytheinventor** [comment]
That's just how Minecraft behaves, it happens with vanilla sounds too. I think the sound engine just cancels all playing sounds when volume = 0%.
