### ISSUE TITLE
Datapack and Resource pack loads, but the disc are not there

### ISSUE THREAD

**Issue by Jedicatt** [TeamTernate/infinite-music-discs#4]

**Comment by bradytheinventor** [comment]
Please give more details about your problem. How many tracks did you add? Can you provide screenshots? What file format was your music in?

**Comment by Jedicatt** [comment]
I added 1 track to test it and it was in .ogg

**Comment by bradytheinventor** [comment]
When you say "the discs are not there", what do you mean exactly? Are you talking about the creative menu? As drops from creepers?

**Comment by Roidan** [comment]
> 
> 
> When you say "the discs are not there", what do you mean exactly? Are you talking about the creative menu? As drops from creepers?

piggy backing off this issue to say that I'm having the same issue, the discs simply don't drop from creepers and don't show up in the Creative inventory.

**Comment by bradytheinventor** [comment]
> piggy backing off this issue to say that I'm having the same issue, the discs simply don't drop from creepers and don't show up in the Creative inventory.

Not dropping from creepers might just be bad luck, depends on how many discs you have.
The discs will not show up in the Creative menu due to Minecraft limitations, so you'll have to get them with commands like I showed in the [instruction video](https://www.youtube.com/watch?v=zDXSKYvJXmg).
