### ISSUE TITLE
Purple and Black Missing Textures 1.19

### ISSUE THREAD

**Issue by RequiredSpace** [TeamTernate/infinite-music-discs#47]
As the Title suggests, When applying the ResourcePack, the music plays but this texture issue is hard to look past.
![2022-09-05_16 22 37](https://user-images.githubusercontent.com/112881425/188471698-66ae7598-31f4-45a3-8f10-1d5091956aa5.png)

**Comment by RequiredSpace** [comment]
Hope you have a great day!!
Thank you for this Amazing tool!

**Comment by bradytheinventor** [comment]
This is weird, usually if something is wrong with the resourcepack it just fails to load and the discs look like "11". Maybe something is wrong with your disc texture? How many discs are in your pack? Do all of them have a purple and black texture? Do you have other texture packs installed?

You could also try generating a pack using the "example-disc.png" texture that comes with the app, just to make sure that works.

**Comment by RequiredSpace** [comment]
I'll try it! Thank you

**Comment by RequiredSpace** [comment]
It worked! :) I Believe the issue might be the size of my png, I just realized the pixel count.

**Comment by RequiredSpace** [comment]
Fixed that was exactly the problem
