### ISSUE TITLE
Multiplayer TPS issues

### ISSUE THREAD

**Issue by saviocao** [TeamTernate/infinite-music-discs#53]
When playing on multiplayer, tps drops by 2-4 for each additional player. I think this is a problem with an on tick function, where it checks every tick for every player something.

**Comment by bradytheinventor** [comment]
Yeah, there are a few per-player checks that run every tick. I'm planning to rewrite the datapack soonish to fix some bugs and improve performance, reducing the number of checks per tick will be a priority for sure.

**Comment by bradytheinventor** [comment]
The new datapack implementation uses fewer per-player checks and fewer per-tick functions, and also uses function trees to reduce commands per tick when nothing needs to run. It should be more efficient now. The new datapack is available in release v1.5
