### ISSUE TITLE
Idk if it’s just a minecraft thing but the music doesn’t stop when the jukebox is broken

### ISSUE THREAD

**Issue by TheCheddarCheese** [TeamTernate/infinite-music-discs#55]
https://user-images.githubusercontent.com/124603704/217030933-b2aa4b4d-5f1d-443f-a4ba-fd3d0c96de4b.mp4

**Comment by bradytheinventor** [comment]
Yeah, this is a bug in the datapack implementation. I'm planning to fix it with a datapack rewrite, which will hopefully come soon-ish.

**Comment by srAlphaPatinton** [comment]
You can fix it if in the app settings u use the Mono option

**Comment by bradytheinventor** [comment]
Fixed in v1.5
