### ISSUE TITLE
Incompability?

### ISSUE THREAD

**Issue by srAlphaPatinton** [TeamTernate/infinite-music-discs#57]
I use this datapack on a server and I add another data pack that needs to change the sound. json if it overwrites this datapack don't work, but if don't the other datapack also don't work, I need the sound. json in the same texture pack BC we are on a server

**Comment by bradytheinventor** [comment]
I think the official Minecraft-intended way to have 2 custom `sounds.json` files is to use 2 resourcepacks so they can
stack. If you can't use 2 resourcepacks, your only option would be to manually merge the 2 `sounds.json` files into a single
file and use that in your resourcepack.

**Comment by srAlphaPatinton** [comment]
i try that but only one works, that its yours

https://www.dropbox.com/s/dy6xu5rdhaaj36o/Desktop.zip?dl=0
Here is the resource pack, if u can help me with the sounds.json

**Comment by srAlphaPatinton** [comment]
problem fixed, Ty love ur datapack
