### ISSUE TITLE
Work with hoppers going into jukeboxes?

### ISSUE THREAD

**Issue by metagn** [TeamTernate/infinite-music-discs#58]
Since 1.19.4 you can put music discs into jukeboxes, however with the custom music discs this just makes the vanilla 11 track play. Is there a way to make it work?

**Comment by bradytheinventor** [comment]
Not yet but I'm working on a datapack rewrite that will add this feature and fix some other bugs. Keep an eye out for the next update!

**Comment by bradytheinventor** [comment]
Fixed in v1.5
