### ISSUE TITLE
Add watchdog timer to generator thread

### ISSUE THREAD

**Issue by Tazluke** [TeamTernate/infinite-music-discs#6]
All 14 files are mp3 and it was working before. when I loaded in a few new songs after it worked the first time it stopped working, so I removed the new files and it continued to not work 

This was what it stayed at for multiple hours before I closed the app
![stuck here](https://user-images.githubusercontent.com/90287278/132413730-9fc55727-1fef-48a3-8070-9fbba5161283.jpg)

**Comment by Tazluke** [comment]
by this I mean it worked once then it stopped working after that. even after removing everything and trying with the files that worked before it still refused to work

**Comment by bradytheinventor** [comment]
I don't know what caused this particular problem, but I can at least try to prevent it from locking up the app.

**Comment by bradytheinventor** [comment]
Should be fixed by ba82e08d74bd77064d34a0b7914a6946cb11e934 and 2fdfbe73aa36d22ab75dbca408a25ab5e249dae9. Adding a watchdog timer in Python is surprisingly hard, so these fixes will have to do for now.
