### ISSUE TITLE
Stops generating at around 80%

### ISSUE THREAD

**Issue by Tduclii** [TeamTernate/infinite-music-discs#61]
When I try to generate it always gets stuck around 80% of the way.

**Comment by bradytheinventor** [comment]
Hmm, I thought I fixed this problem. Can you give me a little more information?

What app version are you using? What OS (windows or linux) and did you download from the release or build it from the source code? What kind of music files (mp3 ogg wav) were you using for your discs? Did you change any settings?

**Comment by Tduclii** [comment]
Oh, I just realised that there is a new version, so sorry for taking your time.
