### ISSUE TITLE
How do I get the discs in Survival?

### ISSUE THREAD

**Issue by dominiko502** [TeamTernate/infinite-music-discs#62]
Sorry for the dumb question, but how do I get the discs in survival?

**Comment by bradytheinventor** [comment]
The same way you get vanilla music discs: get a skeleton to kill a creeper, and the creeper will drop a random music disc (has the chance to drop a custom music disc). The disc drop chances are uniform, so every disc has equal probability to drop, so if you added lots of new discs it will be harder to get a particular disc.

**Comment by TomerGamerTV** [comment]
> The same way you get vanilla music discs: get a skeleton to kill a creeper, and the creeper will drop a random music disc (has the chance to drop a custom music disc). The disc drop chances are uniform, so every disc has equal probability to drop, so if you added lots of new discs it will be harder to get a particular disc.

you know how i can get it in creative? i dont see any of the custom music discs

**Comment by bradytheinventor** [comment]
> you know how i can get it in creative? i dont see any of the custom music discs

`/function infinite_music_discs_dp:give_all_discs` to give yourself everything
`/function infinite_music_discs_dp:give_<name>` to give yourself a specific disc. `<name>` is the internal name of your disc, which you can see as the automatically-generated subtitle of your track when you're building your pack in the app
