### ISSUE TITLE
Discs obtained in survival appear broken

### ISSUE THREAD

**Issue by 890023342** [TeamTernate/infinite-music-discs#65]
I'm kinda new to datapacks but when a skeleton kills a creeper in survival it drops the disc with my sound file name (all correct), but the disc appears broken like Disc 11 and doesn't play the sound file in a jukebox

**Comment by bradytheinventor** [comment]
The tool generates two folders: a datapack and a resourcepack. Make sure you have both installed and the resourcepack is enabled, otherwise you won't see the custom textures or hear your custom music

**Comment by 890023342** [comment]
I removed another datapack that I think was conflicting and now it works fine. Thanks!
