### ISSUE TITLE
CustomModelData Lore

### ISSUE THREAD

**Issue by d4v1ddr0dr1gu3s** [TeamTernate/infinite-music-discs#80]
When i do trigger CustomModelData set 1 on the music disc 11 it changes texture and plays the music that i wanted but it does not change the lore to the name like it still appears C418 - 11 insted of the name that i putted and is not easy to find  what you want on a chest full of discs

**Comment by bradytheinventor** [comment]
Hold the disc whose lore you want to update in your main hand, then run `/function <datapack name>:set_disc_track` to set its lore (it looks at the CustomModelData to detect which lore to use). If you need to update lots of discs it will be easier to run `/function <datapack name>:give_all_discs` which gives you the discs with the lore already set correctly.
