### ISSUE TITLE
.ogg music files 'not converting to ogg' after enabling play from jukebox

### ISSUE THREAD

**Issue by ThatRandomPerson1** [TeamTernate/infinite-music-discs#81]
Hello! I'm here to report a issue where whenever I enable play from jukebox in the application and try to generate, it says it's unable to convert some files in ogg, even if the files are a ogg file.
I also have tried to put in MP3 files in, and that also doesn't work.

Whenever I unenable the option and try to generate, it successfully generates. 
To summarize, whenever I enable play from jukebox and try to generate, it'll give me a error of being unable to convert some files into ogg, even if the files are ogg.

Datapack Application is V1.5
Seems to effect all game versions

Microsoft Windows 10 Pro
10.0.19045 Build 19045
System Type	x64-based PC
Processor	Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, 3192 Mhz, 4 Core(s), 4 Logical Processor(s)

**Comment by bradytheinventor** [comment]
This is a bug. It should be fixed by v1.6 of the app, which was just released!
