### ISSUE TITLE
generator stuck at 99%

### ISSUE THREAD

**Issue by C0smoPlays** [TeamTernate/infinite-music-discs#83]
I've tried 3 times now to make a pack, I've made custom disk files and everything yet it get's stuck at 99% for hours and does nothing, any fixes?

**Comment by bradytheinventor** [comment]
Did the app create any log files? They would be in the same directory as the app and have the word "exception" in their title. If so please send them to me.

This sounds like something went wrong while FFmpeg was processing your music files. Did you move or delete any files while the app was working on your pack? What file format did you use for your images and music files? Did you use a youtube-to-mp3 converter to get your music files (that has caused problems in the past)? Any information you can give me will be helpful.

**Comment by C0smoPlays** [comment]
wasn't able to find any logs but I used mp3 files, should I be converting to .ogg before I attempt to create the pack?
