### ISSUE TITLE
Music disc only playing 11 even with resource pack and replacing the juke box

### ISSUE THREAD

**Issue by Lele8605** [TeamTernate/infinite-music-discs#86]
So I made a custom disc on my 1.19.3 fabric server. I have the resource pack installed and I replaced the juke box multiple times as the info said, but I still only hear 11. Can someone help with this issue?

**Comment by bradytheinventor** [comment]
I haven't been able to reproduce this, but it seems like other people have been having similar problems. Going to close this and move the discussion to #119
