### ISSUE TITLE
command wont run in aternos

### ISSUE THREAD

**Issue by RISHABH4437** [TeamTernate/infinite-music-discs#92]
i have added the rp and dp both to aternos world but idk why i am unable to run the /function command as well as CustomModelData:1 command

**Comment by bradytheinventor** [comment]
The datapack works fine for me on aternos, I just tested it. If you're on a server then you'll need to be op before you can run commands, or you'll need to get the server owner to run the commands for you. (You can op yourself from the aternos console on the website.) And of course you can always kill creepers to get the music discs whether you're op or not.
