### ISSUE TITLE
Question about loot tables

### ISSUE THREAD

**Issue by al-eggs** [TeamTernate/infinite-music-discs#94]
Hello! I'm thinking about using this datapack on a server to get around the 1.19.4 issue with music discs cutting off. I was wondering if there was a way of adding custom discs from this datapack to loot tables (and removing them from the creeper drop pool,) because I want to make some discs more valuable than others. Thanks in advance!

**Comment by bradytheinventor** [comment]
RIght now the tool can only add your custom discs to the creeper drop loot table. But you can edit the datapack after it's generated to remove the discs from the creeper loot table or add them to any other loot table. You can use the creeper loot table as a reference for how the loot table needs to be formatted to generate the discs properly.

**Comment by al-eggs** [comment]
Thanks!
