### ISSUE TITLE
failed to detect ogg file lenght

### ISSUE THREAD

**Issue by MrBanana212** [TeamTernate/infinite-music-discs#95]
hello i would like to know why this error keep hapening and the maximum/ minimum time can a disc have

**Comment by bradytheinventor** [comment]
This is a bug, it should be fixed if you download v1.6 of the app. There shouldn't be any limit to how long/short your tracks can be. I guess technically the max length would be 2^31-1 Minecraft ticks long, but realistically you're probably not going to generate a 30-thousand-hour-long track.
