### ISSUE TITLE
never generated

### ISSUE THREAD

**Issue by Cubbroo** [TeamTernate/infinite-music-discs#97]
Everytime I hit generate, I can't find my file. I saw the previous post about this issue but I tried on both windows 10 and 11 with ogg and mp3 files and nothing worked. I'm trying to make a 1.20.1 pack.

**Comment by bradytheinventor** [comment]
What app version are you using? Does the app finish generating, and if it does do you get a red error message or a green "success" message? If you get a success message your pack files will be placed next to the executable you ran; if you got an error message please tell me what it says and upload any log files the app generated (they would be next to the executable and have "exception" in their name).
